[phases.setup]
nixPkgs = ["nodejs_22_13"]

[phases.install]
cmds = [
    "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash",
    ". ~/.nvm/nvm.sh",
    "nvm install 22.13.1",
    "nvm use 22.13.1",
    "corepack enable && yarn install --frozen-lockfile"
]