dist: xenial
language: node_js
node_js:
- '12'
- '10'
- '8'
cache: yarn
services:
- mysql
branches:
  only:
    - master
    - 2.x
env:
  matrix:
  - DB=sqlite3 NODE_ENV=testing
  - DB=mysql NODE_ENV=testing-mysql
install:
- yarn
before_script:
- if [ $DB == "mysql" ]; then mysql -e 'create database ghost_testing'; fi
- if [ "$DB" == "sqlite3" ]; then yarn add --force sqlite3; fi
script: |
  if [[ "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^renovate || "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
    yarn ci:regression
  elif [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    grunt test-all --verbose
  else
    yarn ci
  fi
notifications:
  slack:
    if: type = cron
    rooms:
      - secure: KzvGpf6RFHgQ3BkppKM4OejFjJYxH60KkDDShet0a0v+j/03HF5Nx0S0Vl9O/F2dPt2qWvblKb3j9EKgB7RsoFSdZuOk7ijA9Duvn+p9RrLom0C9JxOA3ob065WAGyE0OGRm1P5H98loX/L+6oOHC4/qqGKXgz6gUdBtZBn/yo8=
    on_success: change
    on_failure: always
    on_pull_requests: false
