dist: xenial
language: node_js
node_js:
- '10'
- '8'
- '6'
cache: yarn
services:
- mysql
env:
  matrix:
  - DB=sqlite3 NODE_ENV=testing
  - DB=mysql NODE_ENV=testing-mysql
matrix:
  include:
  - node_js: '10'
    env: TEST_SUITE=lint
  fast_finish: true
branches:
  except:
  - "/^renovate\\/.+$/"
install:
- yarn
before_script:
- if [ $DB == "mysql" ]; then mysql -e 'create database ghost_testing'; fi
- if [ "$DB" == "sqlite3" ]; then yarn add --force sqlite3; fi
script: |
  if [ "$TEST_SUITE" == "lint" ]; then
    yarn lint
  elif [[ "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^renovate || "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
    yarn ci:regression
  else
    yarn ci
  fi
notifications:
  slack:
    rooms:
      - secure: KzvGpf6RFHgQ3BkppKM4OejFjJYxH60KkDDShet0a0v+j/03HF5Nx0S0Vl9O/F2dPt2qWvblKb3j9EKgB7RsoFSdZuOk7ijA9Duvn+p9RrLom0C9JxOA3ob065WAGyE0OGRm1P5H98loX/L+6oOHC4/qqGKXgz6gUdBtZBn/yo8=
    on_success: change
    on_failure: always
    on_pull_requests: false
