language: node_js
node_js:
  - "0.10"
env:
  - DB=sqlite3
  - DB=mysql
  - DB=pg
matrix:
  allow_failures:
    - env: DB=pg
before_install:
  - git submodule update --init
  - gem update --system
  - gem install sass bourbon
  - npm install -g grunt-cli
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.1-beta1
  - export PATH=$PATH:`pwd`/bin
  - cd -
  - if [ $DB == "mysql" ]; then mysql -e 'create database ghost_travis'; fi
  - if [ $DB == "pg" ]; then psql -c 'create database ghost_travis;' -U postgres; fi
before_script:
  - phantomjs --version
  - casperjs --version
  - grunt init
