hightlighter: rouge
permalinks: pretty
relative_permalinks: false
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국어'
      key: 'ko'
    - name: 'Deutsch'
      key: 'de'
    - name: 'Français'
      key: 'fr'
    - name: 'Polski'
      key: 'pl'
    - name: '日本語'
      key: 'ja'
    - name: 'Italiano'
      key: 'it'
    - name: '繁體中文'
      key: 'zh_TW'
    - name: 'Português'
      key: 'pt_BR'

port:         4478

translations:
  en:
    installation:     'Installation'
    usage:            'Usage'
    email:            'Email'
    themes:           'Themes'
    apps:             'Apps'
    api:              'API'
    translations:     'Translations'
    help:             'Help'
    mac:              'Mac'
    windows:          'Windows'
    linux:            'Linux'
    deploy:           'Deploy'
    upgrading:        'Upgrading'
    troubleshooting:  'Troubleshooting'
    configuration:    'Configuration'
    faq:              'FAQ'
    managing:         'Managing'
    settings:         'Settings'
    writing:          'Writing'
    getting-started:  'Getting Started'
    handlebars:       'Handlebars'
    structure:        'Structure'
    helpers:          'Helpers'
    changelog:        'Change Log'
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
    deploy:       '部署'
    upgrading:    '升级'
    troubleshooting: '纠错 & 常见问题'
    configuration: '配置'
    faq:          'FAQ'
    managing:     '博客管理'
    settings:     '博客设置'
    writing:      '写作'
    back:         '上一章'
    next:         '下一章'
  ko:
    site_title:   'Ghost 사용안내'
    installation: '설치'
    usage:        '사용법'
    email:        '이메일 설정'
    themes:       '테마'
    translations: '번역'
    help:         '도움말'
    deploy:       '배포'
    upgrading:    '업그레이드'
    troubleshooting: '문제 해결'
    configuration: '구성 설정'
    faq: 'FAQ'
    managing: '관리'
    settings: '일반 설정'
    writing: '글 작성'
    back:         '이전'
    next:         '다음'
  de:
    site_title:   'Ghost-Handbuch'
    installation: 'Installation'
    usage:        'Anwendung'
    email:        'E-Mail'
    themes:       'Themen'
    help:         'Hilfe'
    deploy:       'Einsetzen'
    upgrading:    'Aktualisieren'
    troubleshooting: 'Problembehebung'
    configuration: 'Konfiguration'
    faq: 'FAQ'
    managing: 'Verwalten'
    settings: 'Einstellungen'
    writing: 'Schreiben'
  fr:
    site_title:   'Guide Ghost'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Thèmes'
    translations: 'Traductions'
    help:         'Aide'
  pl:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  ja:
    site_title:   'Ghost日本語ガイド'
    installation: 'インストール'
    usage:        '使い方'
    email:        'メール設定'
    themes:       'テーマ'
    help:         'ヘルプ'
    deploy:       'デプロイ'
    upgrading:    'アップグレード'
    troubleshooting: 'トラブルシューティング'
    configuration: '高度な設定'
    settings:     'ブログの設定'
    managing:     '記事の管理'
    writing:      '記事を書く'
    faq:          'Q&A'
  it:
    site_title:   'Guida a Ghost'
    installation: 'Installazione'
    usage:        'Utilizzo'
    email:        'Email'
    themes:       'Temi'
    translations: 'Traduzioni'
    help:         'Aiuto'
    deploy:       'Deploy'
    upgrading:    'Aggiornamento'
    troubleshooting: 'Risoluzione dei Problemi'
  zh_TW:
    site_title:   'Ghost 使用手冊'
    installation: '安裝'
    usage:        '使用說明'
    email:        '電子郵件'
    themes:       '佈景主題'
    translations: '翻譯'
    help:         '說明'
    deploy:       '部署'
    upgrading:    '升级'
    troubleshooting: '疑難排解'
    configuration: '服務底層設定'
    faq:          'FAQ'
    managing:     '部落格管理'
    settings:     '部落格設定'
    writing:      '寫作'
    back:         '上一章'
    next:         '下一章'
  pt_BR:
    site_title:      'Guia Ghost'
    installation:    'Instalação'
    usage:           'Uso'
    email:           'Email'
    themes:          'Temas'
    apps:            'Apps'
    api:             'API'
    translations:    'Traduções'
    help:            'Ajuda'
    mac:             'Mac'
    windows:         'Windows'
    linux:           'Linux'
    deploy:          'Deploy'
    upgrading:       'Atualizando'
    troubleshooting: 'Resolução de Problemas'
    configuration:   'Configuração'
    faq:             'Perguntas Frequentes'
    managing:        'Gerenciamento'
    settings:        'Configurações'
    writing:         'Escrevendo'
    getting-started: 'Começando'
    handlebars:      'Handlebars'
    structure:       'Estrutura'
    helpers:         'Helpers'
    changelog:       'Registro de Alterações'

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org
