pygments:     true
permalinks: pretty
relative_permalinks: false
languages:
    - name: 'English'
      key: 'en'
    - name: 'Español'
      key: 'es'
    - name: '中文'
      key: 'cn'
    - name: 'Português'
      key: 'pt_BR'
port:         4478

translations:
  es:
    site_title:   'Ghost Guide'
    installation: 'Instalación'
    usage:        'uso'
    email:        'Email'
    themes:       'temas'
    help:         'ayudar'
  cn:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件设置'
    themes:       '主题'
    help:         '帮助'
  pt_BR:
    site_title:   'Guia Ghost'
    installation: 'Instalação'
    usage:        'Uso'
    email:        'Email'
    themes:       'Temas'
    help:         'Ajuda'

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org