pygments:     true
permalink:    /:categories/:title
relative_permalinks: false
languages:
    - name: 'English'
      key: 'en'
    - name: 'Espa√±ol'
      key: 'es'
port:         4478

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org