blank_issues_enabled: true
contact_links:
  - name: ðŸš‘ Help & Support
    url: https://forum.ghost.org
    about: Please use the community forum for questions
  - name: ðŸ’¡ Features & Ideas
    url: https://forum.ghost.org/c/Ideas
    about: Please vote for & post new ideas in the the forum
  - name: ðŸ“– Documentation
    url: https://ghost.org/docs/
    about: Tutorials & reference guides for themes, the API and more
