services:
  ghost:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../.yarncache:/home/ghost/.yarncache
    develop:
      watch:
        - path: ../
          action: sync
          target: /home/ghost
          ignore:
            - node_modules/
            - .yarncache/
        - path: yarn.lock
          action: rebuild
    restart: always
    ports:
      - 2368:2368
      - 4200:4200
    environment:
      - DEBUG=${DEBUG:-}
      - APP_FLAGS=${APP_FLAGS:-}
      - server__host=0.0.0.0
      - server__port=2368
      - database__client=mysql2
      - database__connection__host=ghost-full-mysql
      - database__connection__user=root
      - database__connection__password=root
      - database__connection__database=ghost
      - adapters__Redis__host=ghost-full-redis
      - adapters__Redis__host=6379
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: mysql:8.0.35
    container_name: ghost-full-mysql
    # We'll need to look into how we can further fine tune the memory usage/performance here
    command: --innodb-buffer-pool-size=1G --innodb-log-buffer-size=500M --innodb-change-buffer-max-size=50 --innodb-flush-log-at-trx_commit=0 --innodb-flush-method=O_DIRECT
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghost
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -proot ghost -e 'select 1'"
      interval: 1s
      retries: 120
  redis:
    image: redis:7.0
    container_name: ghost-full-redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      retries: 120

volumes:
  mysql-data:
