name: Auto Assign
on:
  pull_request:
    types: [opened, reopened]
jobs:
  automate:
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'TryGhost'
    env:
      FORCE_COLOR: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: gh extension install daniellockyer/gh-auto-assign
      - run: gh auto-assign
